apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ubuntu
            image: ubuntu
            command: 
            - "bin/bash"
            - "-c"
            - "echo Hello from pod $(hostname) at $(date)"
          restartPolicy: Never