apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/javierrodriguez/Documents/Repositorios/CursoMicroservicios/data